---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: voice-manager-secrets
  namespace: voice-manager
spec:
  encryptedData:
    API_KEY: AgAxih5GWkO7E1CFgcFWk4dGpIEigHLCOTpLbBxGU5wQx8qw1Z9hk2+GMEMOtuEXyLLfoyujDG5eeWXqhc8pAz58WIT/lCTd4iR+mEpYKaffSp8nqCCqszViDyq+AuB0U+AzKsd6gJZ1NIOwVQQWn0Afli199L/5fD5g7Edl8VrMXn7K79JYbVh6+gLGiMQr1adhnJIK/nTi+x0yXyrbf5KRDCMRT0v3/dg3Cv6K4g98LXwyc0JSwdYk1/3hqg5d+PRHy3aYNpeHPsBxQB7DZ/UnfNxiByXHqP3aNvHuvebJRGaNnuvVPoDqYjiRywm7Nly4xQBK9kD9helgYHZdqFxWw90JeBbGjA1flTNyY9dF0Z0guShHxpntKIK5XUZ4DW1fD4WsYJn7N67hTnAj9ScCpW+VmEx9lPcP83PwtF7PNvYf6wXq4S05zwFhmBoxj1cZUbhVcPcBeq72e2uNSRrDliutl83c5I36+LGzj5Rv+t0YIrZa8QCCs8M5VtUHAM5MopiGeKxlGqXwGq7tkcRkQvh1fQXEBSCrXhAFRxLoI0aPQ0bGHbm7mmJC1sgfTJdZ/b8NK+KucK7dqmiyAGEpny9jTN1hE/j9AIcQJdmI3aE0qxiKR0U7cyXcWGhxuBeot0+Ct2VOD+bH4nrH5vj6coc42fiTEM1sy9wtRHFbENc5utJcOdOyAtgnFug2nQxFmdwgzB9tvCc0AbNRPFhw+qdHlbLBUMv3
    DB_PASSWORD: AgBpirt/ejZUd7cK7QDXfnXlurk9zmfgW03EreTw9tl/2mwQhJESK2TRuI7z7YLeVTHUPLH0RbNFLYqN9oiw9Hq5YWLJIDdIA9NaQW9Y8bNhMdNsgXdn/reokSQWhAIXyMJ8AXcjuVxVdLv/nVNzAg7vGftFfjmEyU4pLfNXTK5rP2j3PkzN04nIkB2hyB/I0COfm7K6CANeBZ2qRZ4l1t2I7MsFHSVmh+6CLBBEm/yTWIBZQQkzYs6kljS/eXU2Fhg5ybG3Kn4vdHS58QBVtLH0x7wZCqpVjR191yNPh3PZ8RRJ+53YmpVCGsjy6a9Q9G89YhmM87/niCcS+xV2fJ6+9EURcjfyHO0KDJEbrRhzxjIlgi0/xdAHMhKs5zoeonVEB+nqkwhU60J/f3uaVoxulCuNE/4ueQd06LxJZe6xDiZHRzw4lml7OUiCCuRzTP1fNKk+yBkKCK4mONNY5yRKb339uGEGfb2x63hkienhswDekCKgZpVRL5cfy3ax9Y+awopBAkH8Qt0R2TqvBfH1PR17GpFtmLf5Y+LTeIW0UtXcHEXd62wNTUB5ayWFijoUNHxldfsldiczfppMoIQCPBoR+Yl9u52JVoe1WUA6mhJ+FU2UGFfnZfwiRi3O0dD0KL8S4k4F1/c4uGFtntT2zhmJWU8luqUi4L3Iug8TwMVpHGaWlfSLUW5ykaAuI+7eBBMeq3UVMtE=
  template:
    metadata:
      name: voice-manager-secrets
      namespace: voice-manager
