apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-manager
  namespace: voice-manager
  labels:
    app: voice-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voice-manager
  template:
    metadata:
      labels:
        app: voice-manager
    spec:
      containers:
        - name: voice-manager
          image: ghcr.io/dongshengbc/voice-manager:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
