---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: voice-manager-secrets
  namespace: voice-manager
spec:
  encryptedData:
    API_KEY: AgCpR9Cg8CxOh/wPf78VKY3Cn5wacNEH7rAZHw7lA/RuBhQjcSubR3/1f2ZmrKyf2yZev/kcONx5dA3rCUxgLzin9AMp3Mir5Fk0F8u1s9T2Lj32QP+8xa13RBcfPabSG19LtlwVGT/L2QIVXs9IaGsEyTEGK2nuY7+bDIeoEgZvOZtp8e/8CqSg/iLSB4uggrimBM4vKCO0LJyxXJrs+VYJWQMedgFbI3holQ6mg3B/VSifUQI7xvV6Ad3mveP5bPW2bvm+bXdpPU8zAocvr6pqAX9a4XyiuqtCS0mqVr9AtbNiIfWbrSi4VINiCKizHCJhAaL9RbMtP3y7afBxjgkdBtTbAhzteDDWZndP3vhe+8TQnkEGL1QbOGmXuhBtlRE+z7p/amIUPEYm1NiMQEHJCMrbdC0bBVlfHMmKGcPxexfyEwjdV5iI3H+upW7v4LbQsG7Jf+CUUWsU7tkgMGmkqU7Pb9aQYSSLjNxbFfKEruYjNH4YFUOoxkfBmDbO494kdrQrDeyPN0BlGsaYp3vO7wge5YZkZn40TCd74Rk+y8LvLoWmDKU9+whz4lGH4n7XGfUTjAd6Bk3Ae69/vErEqs8wJnfXpHhGbYY4UcV0JBesPH4SAa1/PgQJss8EsnU3LBJK8pJQ9JxXDRMwDoUF0aDIXXatx7ZTY9DdovwdGoTzn2fv/n+5FOq2tY3VXSeph40PRqCTyj+LQ9aJ++U81nJtTzGLLyYl
    DB_PASSWORD: AgBFNZ5D2ceFBoPD/E9I1j5mDNZ8MXcW2qEBwTCibQJm/QgvCW3a24aayaWU09aQwH3I6dN6EXeopgSr2nX3xSjc6dPXpH1E29kkPpDcc3OkGgMHB3uN0KC4CfHB+KOYTA+0Lh5QSsawKU7aPC195RaJG6e7NIS+Yfpyk733cDSUkLKvQ45aG1DJZ3IueyYu4QVSuMdE74DW/j24A7hokxepLjS7vl2LAGh2mSd5l31z+t0l9x+XLKw7PuyEAOmJnOCWAHWj9aVQBqIkkurLVIYZ3nprhlvrf+B7amJbOLA/XPAZCzBNdjeyk8UbUdz4jdZJ6FlVi436FWedE8n1aGUm2LN0lQqNeBPTOJnF66y/WIMqE+F9RX59M/9Y8THDFUtpkPb1eo4Uxf6q1ya59VHlFfmZGwWzxWnWSGDm10ZH3+VIiNo5TTF7VdW9SiRABHsjXPHO9qxhErykfQjpaAAEz0v89KJaShrESnvlswtKtvH0DR0aNnlXvtiYubYZQjjtjC/3SJxpjYcHvmc7mbLX4zzzDwLsXucc4+nEF0OcZ9Yq4lHdNvQJy6ty1SWk7WGz8NjtQNWusvGQ+yhjjSaCXJHvf5UtjMljxzbR/+wkF7UqbxbicK4yJxLy/X4QVYbLB24AhsSPjj89qGU1hHFOCjTSMx4mEr9hDTEUOfFE4/rtNHya++t5p4BKGZCvO1qY9RuHcSISCMI=
  template:
    metadata:
      name: voice-manager-secrets
      namespace: voice-manager
